version: '3'

volumes:
  db:

services:
  php:
    image: gunterthomas/php:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www:rw

  ## stuff
  database:
    hostname: "db.local"
    image: mariadb:10.9.4
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    command:
      --default-authentication-plugin=mysql_native_password
    env_file:
      - database.env

  adminer:
    image: adminer:latest
    ports:
      - "8090:8080"
    environment:
      - ADMINER_DEFAULT_SERVER="db.local"
